// client.go — multi-language SDK client generator for the generator package.
// Supports TypeScript, Dart, and Swift output targets.
package generator

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"servdocs/pkg/parser"
)

// GenerateClientSDK generates a client SDK for doc in the given language (typescript,
// dart, or swift), writing files into outputDir. Returns an error for unsupported langs.
func GenerateClientSDK(doc *parser.SrvDoc, lang, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return err
	}

	switch strings.ToLower(lang) {
	case "typescript", "ts":
		return generateTypeScript(doc, filepath.Join(outputDir, "client.ts"))
	case "dart":
		return generateDart(doc, filepath.Join(outputDir, "client.dart"))
	case "swift":
		return generateSwift(doc, filepath.Join(outputDir, "client.swift"))
	default:
		return fmt.Errorf("unsupported language: %s", lang)
	}
}

func generateTypeScript(doc *parser.SrvDoc, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := io.Writer(f)
	fmt.Fprintln(w, "/* Auto-generated by ServDocs client generator. */")
	fmt.Fprintln(w, "")

	// 1. Generate interfaces
	for _, s := range doc.Structs {
		if s.Description != "" {
			fmt.Fprintf(w, "/** %s */\n", s.Description)
		}
		fmt.Fprintf(w, "export interface %s {\n", s.Name)
		for _, field := range s.Fields {
			tsType := "string"
			fType := strings.ToLower(field.Type)
			switch fType {
			case "int", "integer", "float", "double":
				tsType = "number"
			case "bool", "boolean":
				tsType = "boolean"
			}
			if field.Description != "" {
				fmt.Fprintf(w, "  /** %s */\n", field.Description)
			}
			fmt.Fprintf(w, "  %s: %s;\n", field.Name, tsType)
		}
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
	}

	// 2. Generate Client Class
	fmt.Fprintln(w, "export class APIClient {")
	fmt.Fprintln(w, "  constructor(private baseUrl: string) {}")
	fmt.Fprintln(w, "")

	for _, r := range doc.Routes {
		method := strings.ToUpper(r.Method)
		inputType := "any"
		if r.InputType != "" {
			inputType = r.InputType
		}
		outputType := "any"
		if r.OutputType != "" {
			outputType = r.OutputType
		}

		// Method name: e.g. "postUserId"
		methodName := strings.ToLower(method) + strings.ReplaceAll(strings.Title(strings.ReplaceAll(r.Path, "/", " ")), " ", "")
		methodName = strings.ReplaceAll(methodName, ":", "")

		if r.Description != "" {
			fmt.Fprintf(w, "  /** %s */\n", r.Description)
		}

		fmt.Fprintf(w, "  async %s(body?: %s): Promise<%s> {\n", methodName, inputType, outputType)
		fmt.Fprintf(w, "    const response = await fetch(`${this.baseUrl}%s`, {\n", r.Path)
		fmt.Fprintf(w, "      method: '%s',\n", method)
		fmt.Fprintf(w, "      headers: { 'Content-Type': 'application/json' },\n")
		fmt.Fprintf(w, "      body: body ? JSON.stringify(body) : undefined\n")
		fmt.Fprintf(w, "    });\n")
		fmt.Fprintln(w, "    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);")
		fmt.Fprintln(w, "    return response.json();")
		fmt.Fprintln(w, "  }")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "}")
	return nil
}

func generateDart(doc *parser.SrvDoc, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := io.Writer(f)
	fmt.Fprintln(w, "/* Auto-generated by ServDocs client generator. */")
	fmt.Fprintln(w, "import 'dart:convert';")
	fmt.Fprintln(w, "import 'package:http/http.dart' as http;")
	fmt.Fprintln(w, "")

	// 1. Generate Models
	for _, s := range doc.Structs {
		fmt.Fprintf(w, "class %s {\n", s.Name)
		for _, field := range s.Fields {
			dartType := "String"
			fType := strings.ToLower(field.Type)
			switch fType {
			case "int", "integer":
				dartType = "int"
			case "float", "double":
				dartType = "double"
			case "bool", "boolean":
				dartType = "bool"
			}
			fmt.Fprintf(w, "  final %s %s;\n", dartType, field.Name)
		}
		fmt.Fprintln(w, "")
		// Constructor
		fmt.Fprintf(w, "  %s({\n", s.Name)
		for _, field := range s.Fields {
			fmt.Fprintf(w, "    required this.%s,\n", field.Name)
		}
		fmt.Fprintln(w, "  });")
		fmt.Fprintln(w, "")

		// FromJson
		fmt.Fprintf(w, "  factory %s.fromJson(Map<String, dynamic> json) {\n", s.Name)
		fmt.Fprintf(w, "    return %s(\n", s.Name)
		for _, field := range s.Fields {
			dartType := "String"
			fType := strings.ToLower(field.Type)
			switch fType {
			case "int", "integer":
				dartType = "int"
			case "float", "double":
				dartType = "double"
			case "bool", "boolean":
				dartType = "bool"
			}
			fmt.Fprintf(w, "      %s: json['%s'] as %s,\n", field.Name, field.Name, dartType)
		}
		fmt.Fprintln(w, "    );")
		fmt.Fprintln(w, "  }")
		fmt.Fprintln(w, "")

		// ToJson
		fmt.Fprintln(w, "  Map<String, dynamic> toJson() => {")
		for _, field := range s.Fields {
			fmt.Fprintf(w, "    '%s': %s,\n", field.Name, field.Name)
		}
		fmt.Fprintln(w, "  };")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
	}

	// 2. Generate Client
	fmt.Fprintln(w, "class APIClient {")
	fmt.Fprintln(w, "  final String baseUrl;")
	fmt.Fprintln(w, "  APIClient(this.baseUrl);")
	fmt.Fprintln(w, "")

	for _, r := range doc.Routes {
		method := strings.ToUpper(r.Method)
		inputType := "dynamic"
		if r.InputType != "" {
			inputType = r.InputType
		}
		outputType := "dynamic"
		if r.OutputType != "" {
			outputType = r.OutputType
		}

		methodName := strings.ToLower(method) + strings.ReplaceAll(strings.Title(strings.ReplaceAll(r.Path, "/", " ")), " ", "")
		methodName = strings.ReplaceAll(methodName, ":", "")

		fmt.Fprintf(w, "  Future<%s> %s([%s? body]) async {\n", outputType, methodName, inputType)
		fmt.Fprintf(w, "    final url = Uri.parse('$baseUrl%s');\n", r.Path)
		fmt.Fprintln(w, "    final headers = {'Content-Type': 'application/json'};")
		if method == "GET" {
			fmt.Fprintln(w, "    final response = await http.get(url, headers: headers);")
		} else {
			fmt.Fprintf(w, "    final response = await http.%s(url, headers: headers, body: body != null ? jsonEncode(body) : null);\n", strings.ToLower(method))
		}
		fmt.Fprintln(w, "    if (response.statusCode != 200) throw Exception('Failed request');")
		if r.OutputType != "" {
			fmt.Fprintf(w, "    return %s.fromJson(jsonDecode(response.body) as Map<String, dynamic>);\n", r.OutputType)
		} else {
			fmt.Fprintln(w, "    return jsonDecode(response.body);")
		}
		fmt.Fprintln(w, "  }")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "}")
	return nil
}

func generateSwift(doc *parser.SrvDoc, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := io.Writer(f)
	fmt.Fprintln(w, "/* Auto-generated by ServDocs client generator. */")
	fmt.Fprintln(w, "import Foundation")
	fmt.Fprintln(w, "")

	// 1. Generate Codable structs
	for _, s := range doc.Structs {
		fmt.Fprintf(w, "public struct %s: Codable {\n", s.Name)
		for _, field := range s.Fields {
			swiftType := "String"
			fType := strings.ToLower(field.Type)
			switch fType {
			case "int", "integer":
				swiftType = "Int"
			case "float", "double":
				swiftType = "Double"
			case "bool", "boolean":
				swiftType = "Bool"
			}
			fmt.Fprintf(w, "  public let %s: %s\n", field.Name, swiftType)
		}
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
	}

	// 2. Generate Client Class
	fmt.Fprintln(w, "public class APIClient {")
	fmt.Fprintln(w, "  private let baseUrl: String")
	fmt.Fprintln(w, "  public init(baseUrl: String) { self.baseUrl = baseUrl }")
	fmt.Fprintln(w, "")

	for _, r := range doc.Routes {
		method := strings.ToUpper(r.Method)
		inputType := "Encodable?"
		if r.InputType != "" {
			inputType = r.InputType + "?"
		}
		outputType := "Data"
		if r.OutputType != "" {
			outputType = r.OutputType
		}

		methodName := strings.ToLower(method) + strings.ReplaceAll(strings.Title(strings.ReplaceAll(r.Path, "/", " ")), " ", "")
		methodName = strings.ReplaceAll(methodName, ":", "")

		fmt.Fprintf(w, "  public func %s(body: %s, completion: @escaping (Result<%s, Error>) -> Void) {\n", methodName, inputType, outputType)
		fmt.Fprintf(w, "    guard let url = URL(string: \"\\(baseUrl)%s\") else { return }\n", r.Path)
		fmt.Fprintln(w, "    var request = URLRequest(url: url)")
		fmt.Fprintf(w, "    request.httpMethod = \"%s\"\n", method)
		fmt.Fprintln(w, "    request.setValue(\"application/json\", forHTTPHeaderField: \"Content-Type\")")
		if r.InputType != "" {
			fmt.Fprintln(w, "    if let body = body { request.httpBody = try? JSONEncoder().encode(body) }")
		}
		fmt.Fprintln(w, "    URLSession.shared.dataTask(with: request) { data, _, error in")
		fmt.Fprintln(w, "      if let error = error { completion(.failure(error)); return }")
		fmt.Fprintln(w, "      guard let data = data else { return }")
		if r.OutputType != "" {
			fmt.Fprintf(w, "      do {\n")
			fmt.Fprintf(w, "        let decoded = try JSONDecoder().decode(%s.self, from: data)\n", r.OutputType)
			fmt.Fprintf(w, "        completion(.success(decoded))\n")
			fmt.Fprintf(w, "      } catch { completion(.failure(error)) }\n")
		} else {
			fmt.Fprintln(w, "      completion(.success(data))")
		}
		fmt.Fprintln(w, "    }.resume()")
		fmt.Fprintln(w, "  }")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "}")
	return nil
}
